name: obscontrol_app
description: "MULMEDMUMED - Professional mobile controller and multiview monitor companion for OBS Studio & broadcast production."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  crypto: ^3.0.7
  cupertino_icons: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.3
  mobile_scanner: ^7.4.2
  shared_preferences: ^2.5.5
  wakelock_plus: ^1.8.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
